name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Adjust based on your Node.js version

    - name: Install dependencies
      run: |
        cd frontend
        npm install  # Use npm install to install dependencies from package.json

    - name: Build the React app
      run: |
        cd frontend
        npm run build  # This generates the build in frontend/build/

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: frontend/build
        clean: true  # Cleans the gh-pages branch before deploying
